controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

joint_trajectory_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
